### ISSUE TITLE
Documentation for 'rewrite' seems to be incorrect

### ISSUE THREAD

**Issue by marat-rkh** [arend-lang/site#15]
https://arend-lang.github.io/documentation/standard-tactics/paths-meta

This section says that `rewrite`

> returns `transportInv (\lam x => T[x/a]) p t`.

I think it should be `transport`. Note that the documentation comments in the `arend-lib` mention `transport`:

https://github.com/JetBrains/arend-lib/blob/master/meta/src/main/java/org/arend/lib/StdExtension.java#L169

**Comment by valis** [comment]
No, actually the documentation in StdExtension.java was incorrect. I fixed it.
